name: stay_sunnah
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  floating_action_bubble: ^1.1.4
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.1.0
  get: 4.6.1
  google_fonts: ^2.3.1

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
